
insert into Biblioteca values
("Biblioteca Universitaria di Bologna", "bub.info@unibo.it","http://www.bub.unibo.it/","Via Zamboni, 33-35 Bologna 40126 BO",44.496888812159334, 11.35242160179635,"Sospensione visite guidate A seguito del DPCM del 14 gennaio 2021, le visite guidate alle sale monumentali della biblioteca sono sospese a tempo indeterminato. Scopri i luoghi e i tesori della Biblioteca Universitaria direttamente a casa tua. Norme sui servizi della BUB a seguito Ord. Reg. n. 25 del 3 marzo 2021 Fino al 21 marzo i servizi bibliotecari sono attivi solo per utenti Unibo e solo su prenotazione. Riduzione orario di apertura al pubblico della BUB Per contrastare ulteriormente la riduzione del contagio da Covid19, da venerdì 13 marzo e per tutta la durata della fascia rossa BUB sarà chiusa al pubblico nei pomeriggi di lunedì, mercoledì e venerdì. Consulta la pagina degli orari per maggiori informazioni. "),
("Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali","info.bigiavi@unibo.it","http://bigiavi.sba.unibo.it/","Via delle Belle Arti 33 ; Piazza Scaravilli 1 Bologna 40126 BO", 44.497863979106405, 11.351878097972945,"Dal 1983 nuova denominazione dei BO129 - Istituto di Ragioneria e BO132 - Istituto di Tecnica Economica. Dal 2002 assorbe BO127 Biblioteca della Sezione di merceologia-Area tecnologia e valorizzazione risorse del Dipartimento di discipline economico-aziendali."),
("Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale","bibclinicabianchi.info@unibo.it","http://clinica.sba.unibo.it/","Via Massarenti 9 Bologna 40138 BO", 44.491739867747434, 11.359933045847738,"Nuova denominazione della biblioteca Centralizzata. Istituto di Clinica Medica e Gastroentologia. Dal 1984 assorbe BO334 - Biblioteca dell'Istituto di Radiologia e Radioterapia L. Galvani. Dal 2009 ha assorbito la Biblioteca del Dipartimento di Medicina Clinica e Biotecnologia applicata D.Campanacci (BO339). Dal 2011 ha assorbito il Fondo Librario. Sezione Malattie Infettive. Dipartimento di Medicina Clinica Specialistica e Sperimentale (BO306)"),
("Biblioteca di Medicina. Biblioteca Biomedica","bibbiomed.info@unibo.it","http://biomedica.sba.unibo.it/","Via Filippo Re, 8 Bologna 40126 BO",44.50049332034816, 11.35545321494052,"Dal 2011 ha assorbito la Biblioteca di Scienze Motorie (BO663)"),
("Biblioteca Centrale Roberto Ruffilli del Campus di Forlì","bibliotecaruffilli.info@unibo.it","http://www.unibo.it/it/campus-forli/biblioteche","via S. Pellegrino Laziosi, 13 Forlì 47121 FC", 44.21964505873354, 12.043822732122477,
"Dal 1.1.95 assorbe BO229 Biblioteca della Scuola Superiore di lingue moderne per interpreti e traduttori. Dal 27.5.96 la BO229 torna ad essere autonoma.")
;

insert into Telefono values("Biblioteca Universitaria di Bologna", "051/2088300"),
("Biblioteca Universitaria di Bologna", "051/2088385"),
("Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali", "051/2098092"),
("Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale","051 300061"),
("Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale","051 2086114"),
("Biblioteca di Medicina. Biblioteca Biomedica","051 2091701"),
("Biblioteca di Medicina. Biblioteca Biomedica","051 2091702"),
("Biblioteca Centrale Roberto Ruffilli del Campus di Forlì","0543/374001"),
("Biblioteca Centrale Roberto Ruffilli del Campus di Forlì","051/2086319")
;



insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (1, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (2, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (3, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (4, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (5, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (6, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (7, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (8, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (9, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (10, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (11, 'Biblioteca Universitaria di Bologna', false, true);
/*insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (12, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (13, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (14, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (15, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (16, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (17, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (18, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (19, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (20, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (21, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (22, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (23, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (24, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (25, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (26, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (27, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (28, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (29, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (30, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (31, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (32, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (33, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (34, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (35, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (36, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (37, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (38, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (39, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (40, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (41, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (42, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (43, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (44, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (45, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (46, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (47, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (48, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (49, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (50, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (51, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (52, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (53, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (54, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (55, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (56, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (57, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (58, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (59, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (60, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (61, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (62, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (63, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (64, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (65, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (66, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (67, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (68, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (69, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (70, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (71, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (72, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (73, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (74, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (75, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (76, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (77, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (78, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (79, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (80, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (81, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (82, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (83, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (84, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (85, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (86, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (87, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (88, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (89, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (90, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (91, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (92, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (93, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (94, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (95, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (96, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (97, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (98, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (99, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (100, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (101, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (102, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (103, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (104, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (105, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (106, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (107, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (108, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (109, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (110, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (111, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (112, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (113, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (114, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (115, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (116, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (117, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (118, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (119, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (120, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (121, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (122, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (123, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (124, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (125, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (126, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (127, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (128, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (129, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (130, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (131, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (132, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (133, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (134, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (135, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (136, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (137, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (138, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (139, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (140, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (141, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (142, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (143, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (144, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (145, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (146, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (147, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (148, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (149, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (150, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (151, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (152, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (153, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (154, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (155, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (156, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (157, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (158, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (159, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (160, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (161, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (162, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (163, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (164, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (165, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (166, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (167, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (168, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (169, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (170, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (171, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (172, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (173, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (174, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (175, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (176, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (177, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (178, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (179, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (180, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (181, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (182, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (183, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (184, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (185, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (186, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (187, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (188, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (189, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (190, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (191, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (192, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (193, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (194, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (195, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (196, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (197, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (198, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (199, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (200, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (201, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (202, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (203, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (204, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (205, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (206, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (207, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (208, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (209, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (210, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (211, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (212, 'Biblioteca Universitaria di Bologna', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (213, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (214, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (215, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (216, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (217, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (218, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (219, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (220, 'Biblioteca Universitaria di Bologna', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (221, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (222, 'Biblioteca Universitaria di Bologna', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (223, 'Biblioteca Universitaria di Bologna', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (224, 'Biblioteca Universitaria di Bologna', true, false);


insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (1, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (2, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (3, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (4, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (5, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (6, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (7, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (8, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (9, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (10, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (11, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (12, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (13, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (14, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (15, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (16, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (17, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (18, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (19, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (20, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (21, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (22, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (23, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (24, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, true);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (25, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (26, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', true, false);
insert into Posto_Lettura (Numero, Biblioteca, ReteEthernet, PresaCorrente) values (27, 'Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali', false, false);
*/
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (1, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (2, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (3, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (4, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (5, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (6, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (7, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (8, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (9, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (10, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
/*insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (11, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (12, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (13, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (14, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (15, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (16, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (17, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (18, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (19, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (20, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (21, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (22, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (23, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (24, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (25, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (26, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (27, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (28, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (29, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (30, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (31, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (32, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (33, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (34, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (35, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (36, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (37, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (38, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (39, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (40, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (41, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (42, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (43, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (44, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (45, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (46, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (47, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (48, 'Biblioteca di Medicina. Biblioteca Clinica F. B. Bianchi. Sezione Centrale', false, false);
*/
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (1, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (2, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (3, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (4, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (5, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (6, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (7, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (8, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (9, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (10, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
/*insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (11, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (12, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (13, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (14, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (15, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (16, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (17, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (18, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (19, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (20, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (21, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (22, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (23, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (24, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (25, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (26, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (27, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (28, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (29, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (30, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (31, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (32, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (33, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (34, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (35, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (36, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (37, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (38, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (39, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (40, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (41, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (42, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (43, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (44, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (45, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (46, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (47, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (48, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (49, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (50, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (51, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (52, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (53, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (54, 'Biblioteca di Medicina. Biblioteca Biomedica', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (55, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (56, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (57, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (58, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (59, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (60, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (61, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (62, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (63, 'Biblioteca di Medicina. Biblioteca Biomedica', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (64, 'Biblioteca di Medicina. Biblioteca Biomedica', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (65, 'Biblioteca di Medicina. Biblioteca Biomedica', false, true);

insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (1, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (2, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (3, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (4, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (5, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (6, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (7, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (8, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (9, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (10, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (11, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (12, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (13, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (14, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (15, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (16, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (17, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (18, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (19, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (20, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (21, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (22, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (23, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (24, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (25, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (26, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (27, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (28, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (29, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (30, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (31, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (32, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (33, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (34, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (35, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (36, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (37, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (38, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (39, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (40, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (41, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (42, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (43, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (44, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (45, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (46, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (47, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (48, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (49, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (50, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (51, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (52, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (53, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (54, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (55, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (56, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (57, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (58, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (59, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (60, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (61, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (62, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (63, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (64, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (65, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (66, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (67, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (68, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (69, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (70, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (71, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (72, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (73, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (74, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (75, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (76, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (77, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (78, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (79, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (80, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (81, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (82, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (83, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (84, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (85, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (86, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (87, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (88, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (89, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (90, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (91, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (92, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (93, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (94, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (95, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (96, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (97, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (98, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (99, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (100, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (101, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (102, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (103, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (104, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (105, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (106, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (107, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (108, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (109, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (110, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (111, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (112, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (113, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (114, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (115, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (116, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (117, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (118, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (119, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (120, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (121, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (122, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (123, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (124, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (125, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (126, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (127, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (128, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (129, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (130, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (131, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (132, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (133, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (134, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (135, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (136, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (137, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (138, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (139, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (140, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (141, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (142, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (143, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (144, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (145, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (146, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (147, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (148, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (149, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (150, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (151, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (152, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (153, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (154, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (155, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (156, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (157, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (158, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (159, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (160, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (161, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (162, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (163, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (164, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (165, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (166, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (167, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (168, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (169, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (170, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (171, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (172, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (173, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (174, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (175, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (176, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (177, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (178, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, false);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (179, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', true, true);
insert into Posto_Lettura (Numero , Biblioteca, ReteEthernet, PresaCorrente) values (180, 'Biblioteca Centrale Roberto Ruffilli del Campus di Forlì', false, true);
*/

insert into Cartaceo(Titolo,Autore, Edizione, Genere, AnnoPubblicazione, NumeroPagine, StatoConservazione, StatoPrestito, Scaffale, Biblioteca) values
("Il nome della rosa","Umberto Eco","Illustrata","Romanzo Storico",2014,576,"Ottimo","Disponibile","1A","Biblioteca Universitaria di Bologna"),
("Io non ho paura","Niccolò Ammaniti","Prima","Romanzo",2001,576,"Ottimo","Disponibile","1A","Biblioteca Universitaria di Bologna"),
("Il capitale nel XXI secolo","Thomas Piketty","Prima","Saggio politico",2013,576,"Ottimo","Disponibile","1A","Biblioteca Universitaria di Bologna"),
("1984","George Orwell","Prima","Fantascienza",1950,576,"Ottimo","Disponibile","1A","Biblioteca Universitaria di Bologna"),
("La fattoria degli animali","George Orwell","Prima","Romanzo",1947,576,"Ottimo","Disponibile","1A","Biblioteca Universitaria di Bologna"),
("L'amicizia","Tahar Ben Jelloun","Prima","Romanzo",1947,576,"Scadente","Disponibile","1A","Biblioteca Universitaria di Bologna"),

("Il nome della rosa","Umberto Eco","Illustrata","Romanzo Storico",2014,576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali"),
("Io non ho paura", "Niccolò Ammaniti","Prima","Romanzo",2001,576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali"),
("Il capitale nel XXI secolo","Thomas Piketty","Prima","Saggio politico",2013,576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali"),
("1984","George Orwell","Prima","Fantascienza",1950,576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali"),
("La fattoria degli animali","George Orwell","Prima","Romanzo",1947,576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali"),
("Manifesto Comunista","Karl Marx,Friedrich Engels","Prima","Saggio politico",1918, 576,"Ottimo","Disponibile","1A","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali")
;






insert into Utilizzatore values("ciao@gmail.com","123","Ual","Erio",'1998-12-12',"Prato","123456",now(),"Poliziotto","Attivo");
insert into Amministratore values("amministratore@gmail.com","123","amministratore","de amministris", '1998-12-12', "Prato", "37048511793","AFM","Biblioteca Universitaria di Bologna");
insert into Amministratore values("amministratoreeco@gmail.com","123","amministratore","de amministris", '1998-12-12', "Prato", "37048511793","AFM","Biblioteca Giuseppe Testoni del Dipartimento di Scienze aziendali");
insert into volontario values("volontario@gmail.com","123","volontario","de volontaris", '1998-12-12', "Prato", "37048511793","Bici");
insert into ebook(Titolo, Edizione, Genere, AnnoPubblicazione, Dimensione, Pdf) values
("Algorithms for Dummies","Prima","Saggistica",2017,4850,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Algorithms for Dummies"),
("Bitcoin For Dummies","Prima","Saggistica",2016,3243,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Bitcoin For Dummies"),
("Electronics For Dummies","Prima","Saggistica",2017,3243,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Electronics For Dummies"),
("Networking all in one for dummies","Prima","Saggistica",2013,38756,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Networking all in one for dummies"),
("Nosql for dummies","Prima","Saggistica",2015,3406,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Nosql for dummies"),
("PHP MySQL JavaScript HTML5 All in One For Dummies","Prima","Saggistica",2015,14193,"C:/xampp/htdocs/Ebiblio/pdf_ebook/PHP MySQL JavaScript HTML5 All in One For Dummies"),
("Programming Interviews For Dummies","Prima","Saggistica",2015,5769,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Programming Interviews For Dummies"),
("Raspberry Pi Projects For Dummies","Prima","Saggistica",2015,16700,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Raspberry Pi Projects For Dummies"),
("Robotic process automation for dummies","Prima","Saggistica",2015,3653,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Robotic process automation for dummies"),
("Tableau for dummies","Prima","Saggistica",2015,3406,"C:/xampp/htdocs/Ebiblio/pdf_ebook/Tableau for dummies")
;